openapi: 3.0.0
info:
  title: Secure API
  version: 1.0.0
  description: |
    Complete API documentation for the project involving user management and encrypted data handling, including registration, login, storing, and retrieving encrypted data with Key Management (KMS).
servers:
  - url: http://localhost:5000

paths:
  /api/auth/register:
    post:
      summary: ثبت‌نام کاربر جدید
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: ثبت‌نام موفق
        '400':
          description: نام کاربری تکراری
        '500':
          description: خطای داخلی سرور

  /api/auth/login:
    post:
      summary: ورود کاربر
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: ورود موفق و دریافت JWT
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: اعتبارسنجی ناموفق
        '403':
          description: حساب کاربری قفل شده
        '500':
          description: خطای داخلی سرور

  /api/data:
    post:
      summary: ذخیره داده رمزنگاری‌شده
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
              required:
                - data
      responses:
        '200':
          description: ذخیره موفق
        '401':
          description: توکن معتبر نیست یا ارسال نشده
        '500':
          description: خطای رمزنگاری یا سرور

    get:
      summary: دریافت داده رمزگشایی‌شده کاربر
      security:
        - bearerAuth: []
      responses:
        '200':
          description: بازیابی موفق داده
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
        '401':
          description: دسترسی غیرمجاز
        '500':
          description: خطای رمزگشایی یا سرور

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
